rules = [DisableSyntax]
DisableSyntax.noReturns = true
DisableSyntax.noWhileLoops = true
DisableSyntax.noXml = true
DisableSyntax.noFinalize = true
DisableSyntax.noThrows = true
DisableSyntax.noIsInstanceOf = false
