package kots.oauth2.store.sql

object Schema {

  val migrations: List[Migration] = List(
    Migration(
      1,
      "CREATE TABLE tokens(" +
        "access_hash VARCHAR(64) PRIMARY KEY, refresh_hash VARCHAR(64), " +
        "grant_id VARCHAR(512) NOT NULL, client_id VARCHAR(512) NOT NULL, " +
        "subject VARCHAR(512) NOT NULL, scopes VARCHAR(2048) NOT NULL, " +
        "issued_at TIMESTAMP NOT NULL, access_expires_at TIMESTAMP NOT NULL, " +
        "refresh_expires_at TIMESTAMP, audience VARCHAR(512), actor VARCHAR(512));" +
        "CREATE INDEX tokens_refresh ON tokens(refresh_hash);" +
        "CREATE INDEX tokens_grant ON tokens(grant_id);" +
        "CREATE TABLE token_details(" +
        "access_hash VARCHAR(64) NOT NULL, ord INT NOT NULL, detail_type VARCHAR(512) NOT NULL, " +
        "locations VARCHAR(2048) NOT NULL, actions VARCHAR(2048) NOT NULL, " +
        "fields VARCHAR(4096) NOT NULL, PRIMARY KEY(access_hash, ord));" +
        "CREATE TABLE retired_tokens(" +
        "refresh_hash VARCHAR(64) PRIMARY KEY, grant_id VARCHAR(512) NOT NULL)"
    ),
    Migration(
      2,
      "CREATE TABLE codes(" +
        "code VARCHAR(512) PRIMARY KEY, client_id VARCHAR(512) NOT NULL, " +
        "redirect_uri VARCHAR(512) NOT NULL, subject VARCHAR(512) NOT NULL, " +
        "scopes VARCHAR(2048) NOT NULL, challenge VARCHAR(512), challenge_method VARCHAR(32), " +
        "expires_at TIMESTAMP NOT NULL, resource VARCHAR(512));" +
        "CREATE TABLE code_details(" +
        "code VARCHAR(512) NOT NULL, ord INT NOT NULL, detail_type VARCHAR(512) NOT NULL, " +
        "locations VARCHAR(2048) NOT NULL, actions VARCHAR(2048) NOT NULL, " +
        "fields VARCHAR(4096) NOT NULL, PRIMARY KEY(code, ord));" +
        "CREATE TABLE redeemed_codes(" +
        "code VARCHAR(512) PRIMARY KEY, grant_id VARCHAR(512) NOT NULL);" +
        "CREATE TABLE grants(" +
        "grant_id VARCHAR(512) PRIMARY KEY, client_id VARCHAR(512) NOT NULL, " +
        "subject VARCHAR(512) NOT NULL, scopes VARCHAR(2048) NOT NULL, " +
        "revoked BOOLEAN NOT NULL);" +
        "CREATE TABLE grant_details(" +
        "grant_id VARCHAR(512) NOT NULL, ord INT NOT NULL, detail_type VARCHAR(512) NOT NULL, " +
        "locations VARCHAR(2048) NOT NULL, actions VARCHAR(2048) NOT NULL, " +
        "fields VARCHAR(4096) NOT NULL, PRIMARY KEY(grant_id, ord))"
    ),
    Migration(
      3,
      "CREATE TABLE clients(" +
        "client_id VARCHAR(512) PRIMARY KEY, redirect_uris VARCHAR(4096) NOT NULL, " +
        "scopes VARCHAR(2048) NOT NULL, auth_method VARCHAR(64) NOT NULL, " +
        "secret_hash VARCHAR(64), registration_token_hash VARCHAR(64), secret VARCHAR(512), " +
        "certificate_subject VARCHAR(512), certificate_thumbprint VARCHAR(512));" +
        "CREATE TABLE client_keys(" +
        "client_id VARCHAR(512) NOT NULL, ord INT NOT NULL, kid VARCHAR(512) NOT NULL, " +
        "alg VARCHAR(32) NOT NULL, params VARCHAR(8192) NOT NULL, PRIMARY KEY(client_id, ord));" +
        "CREATE TABLE devices(" +
        "device_code VARCHAR(512) PRIMARY KEY, user_code VARCHAR(64) NOT NULL, " +
        "client_id VARCHAR(512) NOT NULL, scopes VARCHAR(2048) NOT NULL, " +
        "expires_at TIMESTAMP NOT NULL, subject VARCHAR(512), denied BOOLEAN NOT NULL, " +
        "last_polled_at TIMESTAMP, resource VARCHAR(512));" +
        "CREATE INDEX devices_user ON devices(user_code)"
    ),
    Migration(
      4,
      "CREATE TABLE server_keys(" +
        "seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kid VARCHAR(512) NOT NULL, " +
        "alg VARCHAR(32) NOT NULL, params VARCHAR(8192) NOT NULL, retired BOOLEAN NOT NULL);" +
        "CREATE TABLE consents(" +
        "client_id VARCHAR(512) NOT NULL, subject VARCHAR(512) NOT NULL, " +
        "scopes VARCHAR(2048) NOT NULL, PRIMARY KEY(client_id, subject));" +
        "CREATE TABLE pushed_requests(" +
        "request_uri VARCHAR(512) PRIMARY KEY, client_id VARCHAR(512) NOT NULL, " +
        "parameters VARCHAR(8192) NOT NULL, expires_at TIMESTAMP NOT NULL);" +
        "CREATE TABLE audit_events(" +
        "seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(64) NOT NULL, " +
        "client_id VARCHAR(512), subject VARCHAR(512), grant_id VARCHAR(512), active BOOLEAN)"
    )
  )
}
